export interface PopularPlace {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  category: 'business' | 'shopping' | 'entertainment' | 'healthcare' | 'education' | 'transport' | 'residential' | 'landmark';
  subcategory?: string;
  description?: string;
  icon?: string;
  isPopular?: boolean;
  distance?: number;
}

export const HYDERABAD_POPULAR_PLACES: PopularPlace[] = [
  // Business & IT Hubs
  {
    id: 'hitech-city',
    name: 'HITEC City',
    address: 'HITEC City, Madhapur, Hyderabad, Telangana',
    latitude: 17.4458,
    longitude: 78.3789,
    category: 'business',
    subcategory: 'IT Hub',
    description: 'Major IT and business district',
    icon: '🏢',
    isPopular: true,
  },
  {
    id: 'gachibowli',
    name: 'Gachibowli',
    address: 'Gachibowli, Hyderabad, Telangana',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'business',
    subcategory: 'IT Hub',
    description: 'Financial district and IT corridor',
    icon: '🏦',
    isPopular: true,
  },
  {
    id: 'madhapur',
    name: 'Madhapur',
    address: 'Madhapur, Hyderabad, Telangana',
    latitude: 17.4489,
    longitude: 78.3789,
    category: 'business',
    subcategory: 'IT Hub',
    description: 'Tech companies and startups hub',
    icon: '💻',
    isPopular: true,
  },
  {
    id: 'kondapur',
    name: 'Kondapur',
    address: 'Kondapur, Hyderabad, Telangana',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'business',
    subcategory: 'IT Hub',
    description: 'Software companies and tech parks',
    icon: '🏢',
  },
  {
    id: 'cyberabad',
    name: 'Cyberabad',
    address: 'Cyberabad, Hyderabad, Telangana',
    latitude: 17.4458,
    longitude: 78.3789,
    category: 'business',
    subcategory: 'IT Hub',
    description: 'IT and technology hub',
    icon: '💻',
  },
  {
    id: 'financial-district',
    name: 'Financial District',
    address: 'Financial District, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'business',
    subcategory: 'Financial Hub',
    description: 'Major financial and corporate hub',
    icon: '🏦',
  },

  // Shopping & Entertainment
  {
    id: 'banjara-hills',
    name: 'Banjara Hills',
    address: 'Banjara Hills, Hyderabad, Telangana',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'entertainment',
    subcategory: 'Upscale Area',
    description: 'Upscale residential and commercial area',
    icon: '🏘️',
    isPopular: true,
  },
  {
    id: 'jubilee-hills',
    name: 'Jubilee Hills',
    address: 'Jubilee Hills, Hyderabad, Telangana',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'entertainment',
    subcategory: 'Upscale Area',
    description: 'Fashionable neighborhood with restaurants',
    icon: '🍽️',
    isPopular: true,
  },
  {
    id: 'inorbit-mall',
    name: 'Inorbit Mall',
    address: 'Inorbit Mall, HITEC City, Madhapur, Hyderabad',
    latitude: 17.4458,
    longitude: 78.3789,
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Popular shopping and entertainment destination',
    icon: '🛍️',
  },
  {
    id: 'forum-sujana-mall',
    name: 'Forum Sujana Mall',
    address: 'Forum Sujana Mall, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Shopping mall with multiplex and food court',
    icon: '🎬',
  },
  {
    id: 'city-center-mall',
    name: 'City Center Mall',
    address: 'City Center Mall, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Premium shopping destination',
    icon: '🛍️',
  },
  {
    id: 'south-india-mall',
    name: 'South India Mall',
    address: 'South India Mall, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Popular shopping mall in East Hyderabad',
    icon: '🛍️',
  },

  // Hyderabad Metro Stations (Complete List)
  {
    id: 'miyapur-metro',
    name: 'Miyapur Metro Station',
    address: 'Miyapur Metro Station, Miyapur, Hyderabad',
    latitude: 17.4969,
    longitude: 78.3567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Starting point of Blue Line',
    icon: '🚇',
    isPopular: true,
  },
  {
    id: 'jntu-college-metro',
    name: 'JNTU College Metro Station',
    address: 'JNTU College Metro Station, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near JNTU College',
    icon: '🚇',
  },
  {
    id: 'kukatpally-metro',
    name: 'Kukatpally Metro Station',
    address: 'Kukatpally Metro Station, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Kukatpally',
    icon: '🚇',
  },
  {
    id: 'balanagar-metro',
    name: 'Balanagar Metro Station',
    address: 'Balanagar Metro Station, Balanagar, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Balanagar',
    icon: '🚇',
  },
  {
    id: 'moosapet-metro',
    name: 'Moosapet Metro Station',
    address: 'Moosapet Metro Station, Moosapet, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Moosapet',
    icon: '🚇',
  },
  {
    id: 'bharat-nagar-metro',
    name: 'Bharat Nagar Metro Station',
    address: 'Bharat Nagar Metro Station, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Bharat Nagar',
    icon: '🚇',
  },
  {
    id: 'erragadda-metro',
    name: 'Erragadda Metro Station',
    address: 'Erragadda Metro Station, Erragadda, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Erragadda',
    icon: '🚇',
  },
  {
    id: 'esi-hospital-metro',
    name: 'ESI Hospital Metro Station',
    address: 'ESI Hospital Metro Station, Erragadda, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near ESI Hospital',
    icon: '🚇',
  },
  {
    id: 'srnagar-metro',
    name: 'SR Nagar Metro Station',
    address: 'SR Nagar Metro Station, SR Nagar, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in SR Nagar',
    icon: '🚇',
  },
  {
    id: 'ameerpet-metro',
    name: 'Ameerpet Metro Station',
    address: 'Ameerpet Metro Station, Ameerpet, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Major metro interchange station',
    icon: '🚇',
    isPopular: true,
  },
  {
    id: 'punjagutta-metro',
    name: 'Punjagutta Metro Station',
    address: 'Punjagutta Metro Station, Punjagutta, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Punjagutta',
    icon: '🚇',
  },
  {
    id: 'irrum-manzil-metro',
    name: 'Irrum Manzil Metro Station',
    address: 'Irrum Manzil Metro Station, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Irrum Manzil',
    icon: '🚇',
  },
  {
    id: 'khairatabad-metro',
    name: 'Khairatabad Metro Station',
    address: 'Khairatabad Metro Station, Khairatabad, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Khairatabad',
    icon: '🚇',
  },
  {
    id: 'lakdikapul-metro',
    name: 'Lakdikapul Metro Station',
    address: 'Lakdikapul Metro Station, Lakdikapul, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Lakdikapul',
    icon: '🚇',
  },
  {
    id: 'assembly-metro',
    name: 'Assembly Metro Station',
    address: 'Assembly Metro Station, Nampally, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near Assembly',
    icon: '🚇',
  },
  {
    id: 'nampally-metro',
    name: 'Nampally Metro Station',
    address: 'Nampally Metro Station, Nampally, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Nampally',
    icon: '🚇',
  },
  {
    id: 'gandhi-bhavan-metro',
    name: 'Gandhi Bhavan Metro Station',
    address: 'Gandhi Bhavan Metro Station, Abids, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near Gandhi Bhavan',
    icon: '🚇',
  },
  {
    id: 'osmania-medical-college-metro',
    name: 'Osmania Medical College Metro Station',
    address: 'Osmania Medical College Metro Station, Afzalgunj, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near Osmania Medical College',
    icon: '🚇',
  },
  {
    id: 'mgbs-metro',
    name: 'MGBS Metro Station',
    address: 'MGBS Metro Station, Imlibun, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Major bus station and metro interchange',
    icon: '🚇',
    isPopular: true,
  },
  {
    id: 'malakpet-metro',
    name: 'Malakpet Metro Station',
    address: 'Malakpet Metro Station, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Malakpet',
    icon: '🚇',
  },
  {
    id: 'new-market-metro',
    name: 'New Market Metro Station',
    address: 'New Market Metro Station, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near New Market',
    icon: '🚇',
  },
  {
    id: 'musarambagh-metro',
    name: 'Musarambagh Metro Station',
    address: 'Musarambagh Metro Station, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Musarambagh',
    icon: '🚇',
  },
  {
    id: 'dilsukhnagar-metro',
    name: 'Dilsukhnagar Metro Station',
    address: 'Dilsukhnagar Metro Station, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Dilsukhnagar',
    icon: '🚇',
  },
  {
    id: 'chaitanyapuri-metro',
    name: 'Chaitanyapuri Metro Station',
    address: 'Chaitanyapuri Metro Station, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Chaitanyapuri',
    icon: '🚇',
  },
  {
    id: 'victoria-memorial-metro',
    name: 'Victoria Memorial Metro Station',
    address: 'Victoria Memorial Metro Station, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near Victoria Memorial',
    icon: '🚇',
  },
  {
    id: 'lb-nagar-metro',
    name: 'LB Nagar Metro Station',
    address: 'LB Nagar Metro Station, LB Nagar, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in LB Nagar',
    icon: '🚇',
  },
  {
    id: 'durgam-cheruvu-metro',
    name: 'Durgam Cheruvu Metro Station',
    address: 'Durgam Cheruvu Metro Station, HITEC City, Hyderabad',
    latitude: 17.4369,
    longitude: 78.4031,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station near HITEC City',
    icon: '🚇',
  },
  {
    id: 'hitec-city-metro',
    name: 'HITEC City Metro Station',
    address: 'HITEC City Metro Station, HITEC City, Hyderabad',
    latitude: 17.4458,
    longitude: 78.3789,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in HITEC City',
    icon: '🚇',
  },
  {
    id: 'raidurg-metro',
    name: 'Raidurg Metro Station',
    address: 'Raidurg Metro Station, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'transport',
    subcategory: 'Metro Station',
    description: 'Metro station in Raidurg',
    icon: '🚇',
  },

  // Comprehensive Metro Pillars (All Major Pillars in Hyderabad)
  {
    id: 'pillar-1',
    name: 'Pillar 1',
    address: 'Pillar 1, Outer Ring Road, Hyderabad',
    latitude: 17.4969,
    longitude: 78.3567,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 1',
    icon: '📍',
  },
  {
    id: 'pillar-2',
    name: 'Pillar 2',
    address: 'Pillar 2, Outer Ring Road, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 2',
    icon: '📍',
  },
  {
    id: 'pillar-3',
    name: 'Pillar 3',
    address: 'Pillar 3, Outer Ring Road, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 3',
    icon: '📍',
  },
  {
    id: 'pillar-4',
    name: 'Pillar 4',
    address: 'Pillar 4, Outer Ring Road, Hyderabad',
    latitude: 17.4458,
    longitude: 78.3789,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 4',
    icon: '📍',
  },
  {
    id: 'pillar-5',
    name: 'Pillar 5',
    address: 'Pillar 5, Outer Ring Road, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 5',
    icon: '📍',
  },
  {
    id: 'pillar-6',
    name: 'Pillar 6',
    address: 'Pillar 6, Outer Ring Road, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 6',
    icon: '📍',
  },
  {
    id: 'pillar-7',
    name: 'Pillar 7',
    address: 'Pillar 7, Outer Ring Road, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 7',
    icon: '📍',
  },
  {
    id: 'pillar-8',
    name: 'Pillar 8',
    address: 'Pillar 8, Outer Ring Road, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 8',
    icon: '📍',
  },
  {
    id: 'pillar-9',
    name: 'Pillar 9',
    address: 'Pillar 9, Outer Ring Road, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 9',
    icon: '📍',
  },
  {
    id: 'pillar-10',
    name: 'Pillar 10',
    address: 'Pillar 10, Outer Ring Road, Hyderabad',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 10',
    icon: '📍',
  },
  {
    id: 'pillar-11',
    name: 'Pillar 11',
    address: 'Pillar 11, Outer Ring Road, Hyderabad',
    latitude: 17.3833,
    longitude: 78.4011,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 11',
    icon: '📍',
  },
  {
    id: 'pillar-12',
    name: 'Pillar 12',
    address: 'Pillar 12, Outer Ring Road, Hyderabad',
    latitude: 17.3616,
    longitude: 78.4747,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 12',
    icon: '📍',
  },
  {
    id: 'pillar-13',
    name: 'Pillar 13',
    address: 'Pillar 13, Outer Ring Road, Hyderabad',
    latitude: 17.3500,
    longitude: 78.5000,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 13',
    icon: '📍',
  },
  {
    id: 'pillar-14',
    name: 'Pillar 14',
    address: 'Pillar 14, Outer Ring Road, Hyderabad',
    latitude: 17.3400,
    longitude: 78.5200,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 14',
    icon: '📍',
  },
  {
    id: 'pillar-15',
    name: 'Pillar 15',
    address: 'Pillar 15, Outer Ring Road, Hyderabad',
    latitude: 17.3300,
    longitude: 78.5400,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 15',
    icon: '📍',
  },
  {
    id: 'pillar-16',
    name: 'Pillar 16',
    address: 'Pillar 16, Outer Ring Road, Hyderabad',
    latitude: 17.3200,
    longitude: 78.5600,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 16',
    icon: '📍',
  },
  {
    id: 'pillar-17',
    name: 'Pillar 17',
    address: 'Pillar 17, Outer Ring Road, Hyderabad',
    latitude: 17.3100,
    longitude: 78.5800,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 17',
    icon: '📍',
  },
  {
    id: 'pillar-18',
    name: 'Pillar 18',
    address: 'Pillar 18, Outer Ring Road, Hyderabad',
    latitude: 17.3000,
    longitude: 78.6000,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 18',
    icon: '📍',
  },
  {
    id: 'pillar-19',
    name: 'Pillar 19',
    address: 'Pillar 19, Outer Ring Road, Hyderabad',
    latitude: 17.2900,
    longitude: 78.6200,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 19',
    icon: '📍',
  },
  {
    id: 'pillar-20',
    name: 'Pillar 20',
    address: 'Pillar 20, Outer Ring Road, Hyderabad',
    latitude: 17.2800,
    longitude: 78.6400,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 20',
    icon: '📍',
  },
  {
    id: 'pillar-21',
    name: 'Pillar 21',
    address: 'Pillar 21, Outer Ring Road, Hyderabad',
    latitude: 17.2700,
    longitude: 78.6600,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 21',
    icon: '📍',
  },
  {
    id: 'pillar-22',
    name: 'Pillar 22',
    address: 'Pillar 22, Outer Ring Road, Hyderabad',
    latitude: 17.2600,
    longitude: 78.6800,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 22',
    icon: '📍',
  },
  {
    id: 'pillar-23',
    name: 'Pillar 23',
    address: 'Pillar 23, Outer Ring Road, Hyderabad',
    latitude: 17.2500,
    longitude: 78.7000,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 23',
    icon: '📍',
  },
  {
    id: 'pillar-24',
    name: 'Pillar 24',
    address: 'Pillar 24, Outer Ring Road, Hyderabad',
    latitude: 17.2400,
    longitude: 78.7200,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 24',
    icon: '📍',
  },
  {
    id: 'pillar-25',
    name: 'Pillar 25',
    address: 'Pillar 25, Outer Ring Road, Hyderabad',
    latitude: 17.2300,
    longitude: 78.7400,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 25',
    icon: '📍',
  },
  {
    id: 'pillar-26',
    name: 'Pillar 26',
    address: 'Pillar 26, Outer Ring Road, Hyderabad',
    latitude: 17.2200,
    longitude: 78.7600,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 26',
    icon: '📍',
  },
  {
    id: 'pillar-27',
    name: 'Pillar 27',
    address: 'Pillar 27, Outer Ring Road, Hyderabad',
    latitude: 17.2100,
    longitude: 78.7800,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 27',
    icon: '📍',
  },
  {
    id: 'pillar-28',
    name: 'Pillar 28',
    address: 'Pillar 28, Outer Ring Road, Hyderabad',
    latitude: 17.2000,
    longitude: 78.8000,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 28',
    icon: '📍',
  },
  {
    id: 'pillar-29',
    name: 'Pillar 29',
    address: 'Pillar 29, Outer Ring Road, Hyderabad',
    latitude: 17.1900,
    longitude: 78.8200,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 29',
    icon: '📍',
  },
  {
    id: 'pillar-30',
    name: 'Pillar 30',
    address: 'Pillar 30, Outer Ring Road, Hyderabad',
    latitude: 17.1800,
    longitude: 78.8400,
    category: 'landmark',
    subcategory: 'Metro Pillar',
    description: 'Outer Ring Road Pillar 30',
    icon: '📍',
  },

  // Transport Hubs
  {
    id: 'secunderabad-station',
    name: 'Secunderabad Railway Station',
    address: 'Secunderabad Railway Station, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'transport',
    subcategory: 'Railway Station',
    description: 'Major railway station in Hyderabad',
    icon: '🚂',
    isPopular: true,
  },
  {
    id: 'hyderabad-station',
    name: 'Hyderabad Railway Station',
    address: 'Hyderabad Railway Station, Nampally, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Railway Station',
    description: 'Main railway station in Hyderabad',
    icon: '🚂',
    isPopular: true,
  },
  {
    id: 'kacheguda-station',
    name: 'Kacheguda Railway Station',
    address: 'Kacheguda Railway Station, Kacheguda, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'transport',
    subcategory: 'Railway Station',
    description: 'Railway station in Kacheguda',
    icon: '🚂',
  },
  {
    id: 'begumpet-airport',
    name: 'Begumpet Airport',
    address: 'Begumpet Airport, Begumpet, Hyderabad',
    latitude: 17.4432,
    longitude: 78.4732,
    category: 'transport',
    subcategory: 'Airport',
    description: 'Domestic airport terminal',
    icon: '✈️',
  },
  {
    id: 'rajiv-gandhi-airport',
    name: 'Rajiv Gandhi International Airport',
    address: 'Rajiv Gandhi International Airport, Shamshabad, Hyderabad',
    latitude: 17.2403,
    longitude: 78.4294,
    category: 'transport',
    subcategory: 'Airport',
    description: 'International airport',
    icon: '✈️',
    isPopular: true,
  },

  // Healthcare
  {
    id: 'apollo-hospitals',
    name: 'Apollo Hospitals',
    address: 'Apollo Hospitals, Jubilee Hills, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'healthcare',
    subcategory: 'Hospital',
    description: 'Multi-specialty hospital',
    icon: '🏥',
  },
  {
    id: 'kims-hospitals',
    name: 'KIMS Hospitals',
    address: 'KIMS Hospitals, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'healthcare',
    subcategory: 'Hospital',
    description: 'Leading healthcare provider',
    icon: '🏥',
  },
  {
    id: 'yashoda-hospitals',
    name: 'Yashoda Hospitals',
    address: 'Yashoda Hospitals, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'healthcare',
    subcategory: 'Hospital',
    description: 'Multi-specialty hospital chain',
    icon: '🏥',
  },
  {
    id: 'continental-hospitals',
    name: 'Continental Hospitals',
    address: 'Continental Hospitals, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'healthcare',
    subcategory: 'Hospital',
    description: 'Super specialty hospital',
    icon: '🏥',
  },

  // Education
  {
    id: 'iit-hyderabad',
    name: 'IIT Hyderabad',
    address: 'IIT Hyderabad, Kandi, Sangareddy, Telangana',
    latitude: 17.5931,
    longitude: 78.1256,
    category: 'education',
    subcategory: 'University',
    description: 'Indian Institute of Technology',
    icon: '🎓',
  },
  {
    id: 'uoh',
    name: 'University of Hyderabad',
    address: 'University of Hyderabad, Gachibowli, Hyderabad',
    latitude: 17.4619,
    longitude: 78.3489,
    category: 'education',
    subcategory: 'University',
    description: 'Central University',
    icon: '🎓',
  },
  {
    id: 'jntu-hyderabad',
    name: 'JNTU Hyderabad',
    address: 'JNTU Hyderabad, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'education',
    subcategory: 'University',
    description: 'Jawaharlal Nehru Technological University',
    icon: '🎓',
  },
  {
    id: 'osmania-university',
    name: 'Osmania University',
    address: 'Osmania University, Amberpet, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'education',
    subcategory: 'University',
    description: 'State university',
    icon: '🎓',
  },

  // Landmarks & Tourist Attractions
  {
    id: 'charminar',
    name: 'Charminar',
    address: 'Charminar, Old City, Hyderabad, Telangana',
    latitude: 17.3616,
    longitude: 78.4747,
    category: 'landmark',
    subcategory: 'Monument',
    description: 'Iconic monument and symbol of Hyderabad',
    icon: '🏛️',
    isPopular: true,
  },
  {
    id: 'golconda-fort',
    name: 'Golconda Fort',
    address: 'Golconda Fort, Ibrahim Bagh, Hyderabad',
    latitude: 17.3833,
    longitude: 78.4011,
    category: 'landmark',
    subcategory: 'Fort',
    description: 'Historic fort and tourist attraction',
    icon: '🏰',
    isPopular: true,
  },
  {
    id: 'ramoji-film-city',
    name: 'Ramoji Film City',
    address: 'Ramoji Film City, Anaspur, Hyderabad',
    latitude: 17.2511,
    longitude: 78.4396,
    category: 'entertainment',
    subcategory: 'Theme Park',
    description: 'World\'s largest film studio complex',
    icon: '🎬',
    isPopular: true,
  },
  {
    id: 'salar-jung-museum',
    name: 'Salar Jung Museum',
    address: 'Salar Jung Museum, Darulshifa, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'landmark',
    subcategory: 'Museum',
    description: 'Art museum with rare collections',
    icon: '🏛️',
  },
  {
    id: 'birla-mandir',
    name: 'Birla Mandir',
    address: 'Birla Mandir, Naubat Pahad, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'landmark',
    subcategory: 'Temple',
    description: 'Hindu temple on Naubat Pahad',
    icon: '🛕',
  },
  {
    id: 'hussain-sagar',
    name: 'Hussain Sagar',
    address: 'Hussain Sagar, Tank Bund, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'landmark',
    subcategory: 'Lake',
    description: 'Heart-shaped lake with Buddha statue',
    icon: '🏞️',
    isPopular: true,
  },

  // Residential Areas
  {
    id: 'kukatpally',
    name: 'Kukatpally',
    address: 'Kukatpally, Hyderabad, Telangana',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Popular residential locality',
    icon: '🏠',
  },
  {
    id: 'dilsukhnagar',
    name: 'Dilsukhnagar',
    address: 'Dilsukhnagar, Hyderabad, Telangana',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Densely populated residential area',
    icon: '🏠',
  },
  {
    id: 'uppal',
    name: 'Uppal',
    address: 'Uppal, Hyderabad, Telangana',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Growing residential and commercial area',
    icon: '🏠',
  },
  {
    id: 'lb-nagar',
    name: 'LB Nagar',
    address: 'LB Nagar, Hyderabad, Telangana',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area with good connectivity',
    icon: '🏠',
  },
  {
    id: 'malkajgiri',
    name: 'Malkajgiri',
    address: 'Malkajgiri, Hyderabad, Telangana',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area in North Hyderabad',
    icon: '🏠',
  },
  {
    id: 'alwal',
    name: 'Alwal',
    address: 'Alwal, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area in Secunderabad',
    icon: '🏠',
  },
  {
    id: 'bowenpally',
    name: 'Bowenpally',
    address: 'Bowenpally, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area in Secunderabad',
    icon: '🏠',
  },
  {
    id: 'tarnaka',
    name: 'Tarnaka',
    address: 'Tarnaka, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area near Osmania University',
    icon: '🏠',
  },
  {
    id: 'sainikpuri',
    name: 'Sainikpuri',
    address: 'Sainikpuri, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Defense personnel residential area',
    icon: '🏠',
  },
  {
    id: 'kompally',
    name: 'Kompally',
    address: 'Kompally, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Residential Area',
    description: 'Residential area in North Secunderabad',
    icon: '🏠',
  },

  // Hostels and PGs in Hyderabad
  {
    id: 'boys-hostel-kukatpally',
    name: 'Boys Hostel Kukatpally',
    address: 'Boys Hostel, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Kukatpally area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-kukatpally',
    name: 'Girls Hostel Kukatpally',
    address: 'Girls Hostel, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Kukatpally area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-kukatpally',
    name: 'Boys PG Kukatpally',
    address: 'Boys PG, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Kukatpally',
    icon: '🏠',
  },
  {
    id: 'girls-pg-kukatpally',
    name: 'Girls PG Kukatpally',
    address: 'Girls PG, Kukatpally, Hyderabad',
    latitude: 17.4845,
    longitude: 78.4139,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Kukatpally',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-dilsukhnagar',
    name: 'Boys Hostel Dilsukhnagar',
    address: 'Boys Hostel, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Dilsukhnagar area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-dilsukhnagar',
    name: 'Girls Hostel Dilsukhnagar',
    address: 'Girls Hostel, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Dilsukhnagar area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-dilsukhnagar',
    name: 'Boys PG Dilsukhnagar',
    address: 'Boys PG, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Dilsukhnagar',
    icon: '🏠',
  },
  {
    id: 'girls-pg-dilsukhnagar',
    name: 'Girls PG Dilsukhnagar',
    address: 'Girls PG, Dilsukhnagar, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Dilsukhnagar',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-uppal',
    name: 'Boys Hostel Uppal',
    address: 'Boys Hostel, Uppal, Hyderabad',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Uppal area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-uppal',
    name: 'Girls Hostel Uppal',
    address: 'Girls Hostel, Uppal, Hyderabad',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Uppal area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-uppal',
    name: 'Boys PG Uppal',
    address: 'Boys PG, Uppal, Hyderabad',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Uppal',
    icon: '🏠',
  },
  {
    id: 'girls-pg-uppal',
    name: 'Girls PG Uppal',
    address: 'Girls PG, Uppal, Hyderabad',
    latitude: 17.4058,
    longitude: 78.5591,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Uppal',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-lb-nagar',
    name: 'Boys Hostel LB Nagar',
    address: 'Boys Hostel, LB Nagar, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in LB Nagar area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-lb-nagar',
    name: 'Girls Hostel LB Nagar',
    address: 'Girls Hostel, LB Nagar, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in LB Nagar area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-lb-nagar',
    name: 'Boys PG LB Nagar',
    address: 'Boys PG, LB Nagar, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in LB Nagar',
    icon: '🏠',
  },
  {
    id: 'girls-pg-lb-nagar',
    name: 'Girls PG LB Nagar',
    address: 'Girls PG, LB Nagar, Hyderabad',
    latitude: 17.3676,
    longitude: 78.5576,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in LB Nagar',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-malkajgiri',
    name: 'Boys Hostel Malkajgiri',
    address: 'Boys Hostel, Malkajgiri, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Malkajgiri area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-malkajgiri',
    name: 'Girls Hostel Malkajgiri',
    address: 'Girls Hostel, Malkajgiri, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Malkajgiri area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-malkajgiri',
    name: 'Boys PG Malkajgiri',
    address: 'Boys PG, Malkajgiri, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Malkajgiri',
    icon: '🏠',
  },
  {
    id: 'girls-pg-malkajgiri',
    name: 'Girls PG Malkajgiri',
    address: 'Girls PG, Malkajgiri, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Malkajgiri',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-secunderabad',
    name: 'Boys Hostel Secunderabad',
    address: 'Boys Hostel, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Secunderabad area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-secunderabad',
    name: 'Girls Hostel Secunderabad',
    address: 'Girls Hostel, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Secunderabad area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-secunderabad',
    name: 'Boys PG Secunderabad',
    address: 'Boys PG, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Secunderabad',
    icon: '🏠',
  },
  {
    id: 'girls-pg-secunderabad',
    name: 'Girls PG Secunderabad',
    address: 'Girls PG, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Secunderabad',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-ameerpet',
    name: 'Boys Hostel Ameerpet',
    address: 'Boys Hostel, Ameerpet, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Ameerpet area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-ameerpet',
    name: 'Girls Hostel Ameerpet',
    address: 'Girls Hostel, Ameerpet, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Ameerpet area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-ameerpet',
    name: 'Boys PG Ameerpet',
    address: 'Boys PG, Ameerpet, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Ameerpet',
    icon: '🏠',
  },
  {
    id: 'girls-pg-ameerpet',
    name: 'Girls PG Ameerpet',
    address: 'Girls PG, Ameerpet, Hyderabad',
    latitude: 17.4372,
    longitude: 78.4489,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Ameerpet',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-madhapur',
    name: 'Boys Hostel Madhapur',
    address: 'Boys Hostel, Madhapur, Hyderabad',
    latitude: 17.4489,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Madhapur area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-madhapur',
    name: 'Girls Hostel Madhapur',
    address: 'Girls Hostel, Madhapur, Hyderabad',
    latitude: 17.4489,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Madhapur area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-madhapur',
    name: 'Boys PG Madhapur',
    address: 'Boys PG, Madhapur, Hyderabad',
    latitude: 17.4489,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Madhapur',
    icon: '🏠',
  },
  {
    id: 'girls-pg-madhapur',
    name: 'Girls PG Madhapur',
    address: 'Girls PG, Madhapur, Hyderabad',
    latitude: 17.4489,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Madhapur',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-gachibowli',
    name: 'Boys Hostel Gachibowli',
    address: 'Boys Hostel, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Gachibowli area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-gachibowli',
    name: 'Girls Hostel Gachibowli',
    address: 'Girls Hostel, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Gachibowli area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-gachibowli',
    name: 'Boys PG Gachibowli',
    address: 'Boys PG, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Gachibowli',
    icon: '🏠',
  },
  {
    id: 'girls-pg-gachibowli',
    name: 'Girls PG Gachibowli',
    address: 'Girls PG, Gachibowli, Hyderabad',
    latitude: 17.4401,
    longitude: 78.3489,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Gachibowli',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-kondapur',
    name: 'Boys Hostel Kondapur',
    address: 'Boys Hostel, Kondapur, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Kondapur area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-kondapur',
    name: 'Girls Hostel Kondapur',
    address: 'Girls Hostel, Kondapur, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Kondapur area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-kondapur',
    name: 'Boys PG Kondapur',
    address: 'Boys PG, Kondapur, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Kondapur',
    icon: '🏠',
  },
  {
    id: 'girls-pg-kondapur',
    name: 'Girls PG Kondapur',
    address: 'Girls PG, Kondapur, Hyderabad',
    latitude: 17.4701,
    longitude: 78.3789,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Kondapur',
    icon: '🏠',
  },

  // Additional Popular Hostel/PG Areas
  {
    id: 'boys-hostel-banjara-hills',
    name: 'Boys Hostel Banjara Hills',
    address: 'Boys Hostel, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Banjara Hills area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-banjara-hills',
    name: 'Girls Hostel Banjara Hills',
    address: 'Girls Hostel, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Banjara Hills area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-banjara-hills',
    name: 'Boys PG Banjara Hills',
    address: 'Boys PG, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Banjara Hills',
    icon: '🏠',
  },
  {
    id: 'girls-pg-banjara-hills',
    name: 'Girls PG Banjara Hills',
    address: 'Girls PG, Banjara Hills, Hyderabad',
    latitude: 17.4065,
    longitude: 78.4567,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Banjara Hills',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-jubilee-hills',
    name: 'Boys Hostel Jubilee Hills',
    address: 'Boys Hostel, Jubilee Hills, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Jubilee Hills area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-jubilee-hills',
    name: 'Girls Hostel Jubilee Hills',
    address: 'Girls Hostel, Jubilee Hills, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Jubilee Hills area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-jubilee-hills',
    name: 'Boys PG Jubilee Hills',
    address: 'Boys PG, Jubilee Hills, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Jubilee Hills',
    icon: '🏠',
  },
  {
    id: 'girls-pg-jubilee-hills',
    name: 'Girls PG Jubilee Hills',
    address: 'Girls PG, Jubilee Hills, Hyderabad',
    latitude: 17.4229,
    longitude: 78.4078,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Jubilee Hills',
    icon: '🏠',
  },
  {
    id: 'boys-hostel-malakpet',
    name: 'Boys Hostel Malakpet',
    address: 'Boys Hostel, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Boys Hostel',
    description: 'Boys hostel in Malakpet area',
    icon: '🏠',
  },
  {
    id: 'girls-hostel-malakpet',
    name: 'Girls Hostel Malakpet',
    address: 'Girls Hostel, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Girls Hostel',
    description: 'Girls hostel in Malakpet area',
    icon: '🏠',
  },
  {
    id: 'boys-pg-malakpet',
    name: 'Boys PG Malakpet',
    address: 'Boys PG, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Boys PG',
    description: 'Boys paying guest accommodation in Malakpet',
    icon: '🏠',
  },
  {
    id: 'girls-pg-malakpet',
    name: 'Girls PG Malakpet',
    address: 'Girls PG, Malakpet, Hyderabad',
    latitude: 17.3713,
    longitude: 78.5264,
    category: 'residential',
    subcategory: 'Girls PG',
    description: 'Girls paying guest accommodation in Malakpet',
    icon: '🏠',
  },
];

// Helper functions
export const getPlacesByCategory = (category: PopularPlace['category']): PopularPlace[] => {
  return HYDERABAD_POPULAR_PLACES.filter(place => place.category === category);
};

export const getPopularPlaces = (): PopularPlace[] => {
  return HYDERABAD_POPULAR_PLACES.filter(place => place.isPopular);
};

export const searchPlaces = (query: string): PopularPlace[] => {
  const lowercaseQuery = query.toLowerCase();
  return HYDERABAD_POPULAR_PLACES.filter(place =>
    place.name.toLowerCase().includes(lowercaseQuery) ||
    place.address.toLowerCase().includes(lowercaseQuery) ||
    place.description?.toLowerCase().includes(lowercaseQuery) ||
    place.subcategory?.toLowerCase().includes(lowercaseQuery)
  );
};

export const getCategoryIcon = (category: PopularPlace['category']): string => {
  const icons = {
    business: '🏢',
    shopping: '🛍️',
    entertainment: '🎭',
    healthcare: '🏥',
    education: '🎓',
    transport: '🚇',
    residential: '🏠',
    landmark: '🏛️',
  };
  return icons[category] || '📍';
};

// Enhanced icon function for subcategories
export const getSubcategoryIcon = (subcategory?: string): string => {
  if (!subcategory) return '📍';
  
  const subcategoryIcons: { [key: string]: string } = {
    'Boys Hostel': '🏠',
    'Girls Hostel': '🏠',
    'Boys PG': '🏠',
    'Girls PG': '🏠',
    'Metro Pillar': '📍',
    'Metro Station': '🚇',
    'IT Hub': '💻',
    'Shopping Mall': '🛍️',
    'Hospital': '🏥',
    'University': '🎓',
    'Railway Station': '🚂',
    'Airport': '✈️',
    'Monument': '🏛️',
    'Fort': '🏰',
    'Theme Park': '🎬',
    'Museum': '🏛️',
    'Temple': '🛕',
    'Lake': '🏞️',
    'Residential Area': '🏠',
    'Upscale Area': '🏘️',
    'Financial Hub': '🏦',
  };
  
  return subcategoryIcons[subcategory] || '📍';
};

export const getCategoryColor = (category: PopularPlace['category']): string => {
  const colors = {
    business: '#3B82F6', // Blue
    shopping: '#EC4899', // Pink
    entertainment: '#8B5CF6', // Purple
    healthcare: '#EF4444', // Red
    education: '#10B981', // Green
    transport: '#F59E0B', // Amber
    residential: '#6B7280', // Gray
    landmark: '#DC2626', // Red
  };
  return colors[category] || '#6B7280';
};
